from typing import Protocol
from uuid import UUID

class IndexerPort(Protocol):
    def ensure_index(self) -> None: ...
    def upsert(self, doc: dict) -> None: ...
    def delete(self, content_id: UUID) -> None: ...
